#ifndef GLOBAL_ENUMS_H
#define GLOBAL_ENUMS_H

#include "qnamespace.h"

enum VMColors
{
	vmDefault_Color = -1 ,
	vmGray = Qt::gray,
	vmRed = Qt::red,
	vmYellow = Qt::yellow,
	vmGreen = Qt::green,
	vmBlue = Qt::blue,
	vmWhite = Qt::white
};

enum PROCESS_STEPS
{
	PS_PREPARE, PS_EXEC, PS_FINISH, PS_CANCEL
};

static const unsigned int TABLES_IN_DB ( 15 );

enum TABLE_ORDER
{
	TABLE_GENERAL_ORDER = 0, TABLE_USERS_ORDER = 1, TABLE_CLIENT_ORDER = 2, TABLE_JOB_ORDER = 3, TABLE_PAY_ORDER = 4,
	TABLE_BUY_ORDER = 5, TABLE_QP_ORDER = 6, TABLE_SUPPLIES_ORDER = 7, TABLE_SERVICES_ORDER = 8, TABLE_SUPPLIER_ORDER = 9,
	TABLE_CP_ORDER = 10, TABLE_INVENTORY_ORDER = 11, TABLE_COMPLETER_RECORDS_ORDER = 12,
	TABLE_CALENDAR_ORDER = 13, TABLE_MACHINES_ORDER = 14
};

enum TABLE_IDS
{
	GENERAL_TABLE = 2<<0, USERS_TABLE = 2<<1, CLIENT_TABLE = 2<<2, JOB_TABLE = 2<<3,
	PAYMENT_TABLE = 2<<4, PURCHASE_TABLE = 2<<5, QUICK_PROJECT_TABLE = 2<<6,
	SUPPLIES_TABLE = 2<<7, SERVICES_TABLE = 2<<8, SUPPLIER_TABLE = 2<<9,
	COMPANY_PURCHASES_TABLE = 2<<10, INVENTORY_TABLE = 2<<11,
	COMPLETER_RECORDS_TABLE = 2<<12, CALENDAR_TABLE = 2<<13, MACHINES_TABLE = 2<<14
};

enum MESSAGE_INFO
{
	TELL_NONE = 0, TELL_SAVE = 1,
	TELL_CONCLUDED = 100, TELL_EDIT = 101, TELL_ADD = 102, TELL_DEL = 103,
	TELL_EDIT_DONE = 104, TELL_ADD_DONE = 105, TELL_DEL_DONE = 106
};

enum
{
	FLD_CLIENT_ID = 0, FLD_CLIENT_NAME = 1, FLD_CLIENT_STREET = 2, FLD_CLIENT_NUMBER = 3,
	FLD_CLIENT_DISTRICT = 4, FLD_CLIENT_CITY = 5, FLD_CLIENT_ZIP = 6, FLD_CLIENT_PHONES = 7,
	FLD_CLIENT_EMAIL = 8, FLD_CLIENT_STARTDATE = 9, FLD_CLIENT_ENDDATE = 10, FLD_CLIENT_STATUS = 11,

	FLD_JOB_ID = 0, FLD_JOB_CLIENTID = 1, FLD_JOB_TYPE = 2, FLD_JOB_STARTDATE = 3, FLD_JOB_ENDDATE = 4,
	FLD_JOB_TIME = 5, FLD_JOB_PRICE = 6, FLD_JOB_PROJECT_PATH = 7, FLD_JOB_PROJECT_ID = 8,
	FLD_JOB_PICTURE_PATH = 9, FLD_JOB_ADDRESS = 10, FLD_JOB_REPORT = 11,

	FLD_PAY_ID = 0, FLD_PAY_CLIENTID = 1, FLD_PAY_JOBID = 2, FLD_PAY_PRICE = 3,
	FLD_PAY_TOTALPAYS = 4, FLD_PAY_TOTALPAID = 5, FLD_PAY_OBS = 6, FLD_PAY_INFO = 7, FLD_PAY_OVERDUE = 8, FLD_PAY_OVERDUE_VALUE = 9,

	FLD_BUY_ID = 0, FLD_BUY_CLIENTID = 1, FLD_BUY_JOBID = 2, FLD_BUY_DATE = 3, FLD_BUY_DELIVERDATE = 4,
	FLD_BUY_PRICE = 5, FLD_BUY_TOTALPAID = 6, FLD_BUY_TOTALPAYS = 7, FLD_BUY_DELIVERMETHOD = 8, FLD_BUY_SUPPLIER = 9,
	FLD_BUY_NOTES = 10, FLD_BUY_REPORT = 11, FLD_BUY_PAYINFO = 12,

	FLD_GENERAL_ID = 0, FLD_GENERAL_TABLENAME = 1, FLD_GENERAL_TABLEVERSION = 2, FLD_GENERAL_TABLEID = 3, FLD_GENERAL_MOWER_OIL_TIME = 4,
	FLD_GENERAL_CONFIG_FILE = 5, FLD_GENERAL_EXTRA = 6,

	FLD_QP_ID = 0, FLD_QP_JOB_ID = 1, FLD_QP_ITEM = 2, FLD_QP_SELL_QUANTITY = 3, FLD_QP_SELL_UNIT_PRICE = 4,
	FLD_QP_SELL_TOTALPRICE = 5, FLD_QP_PURCHASE_QUANTITY = 6, FLD_QP_PURCHASE_UNIT_PRICE = 7, FLD_QP_PURCHASE_TOTAL_PRICE = 8,
	FLD_QP_RESULT = 9,

	FLD_INVENTORY_ID = 0, FLD_INVENTORY_ITEM = 1, FLD_INVENTORY_BRAND = 2, FLD_INVENTORY_QUANTITY = 3, FLD_INVENTORY_UNIT = 4, FLD_INVENTORY_TYPE = 5,
	FLD_INVENTORY_DATE_IN = 6, FLD_INVENTORY_PRICE = 7, FLD_INVENTORY_SUPPLIER = 8, FLD_INVENTORY_PLACE = 9,

	FLD_SUPPLIES_ID = 0, FLD_SUPPLIES_ITEM = 1, FLD_SUPPLIES_BRAND = 2, FLD_SUPPLIES_QUANTITY = 3, FLD_SUPPLIES_UNIT = 4, FLD_SUPPLIES_TYPE = 5,
	FLD_SUPPLIES_DATE_IN = 6, FLD_SUPPLIES_PRICE = 7, FLD_SUPPLIES_SUPPLIER = 8, FLD_SUPPLIES_PLACE = 9,

	FLD_SERVICES_ID = 0, FLD_SERVICES_TYPE = 1, FLD_SERVICES_BASIC_UNIT = 2, FLD_SERVICES_PRICE_PER_UNIT = 3, FLD_SERVICES_LAST_UPDATE = 4,
	FLD_SERVICES_AVERAGE_TIME = 5, FLD_SERVICES_DISCOUNT_FROM = 6, FLD_SERVICES_DISCOUNT_FACTOR = 7,

	FLD_USER_ID = 0, FLD_USER_INFO = 1, FLD_USER_PRIVILEDGES = 2, FLD_USER_LOCATION = 3, FLD_USER_LOGGED_USERS = 4,

	FLD_SUPPLIER_ID = 0, FLD_SUPPLIER_NAME = 1, FLD_SUPPLIER_STREET = 2, FLD_SUPPLIER_NUMBER = 3, FLD_SUPPLIER_DISTRICT = 4,
	FLD_SUPPLIER_CITY = 5, FLD_SUPPLIER_PHONES = 6, FLD_SUPPLIER_EMAIL = 7,

	FLD_CP_ID = 0, FLD_CP_DATE = 1, FLD_CP_DELIVERY_DATE = 2, FLD_CP_DELIVERY_METHOD = 3,
	FLD_CP_NOTES = 4, FLD_CP_SUPPLIER = 5, FLD_CP_TOTAL_PRICE = 6, FLD_CP_PAY_VALUE = 7,
	FLD_CP_ITEMS_REPORT = 8, FLD_CP_PAY_REPORT = 9,

	FLD_CR_ID = 0, FLD_CR_PRODUCT_OR_SERVICE_1 = 1, FLD_CR_PRODUCT_OR_SERVICE_2 = 2, FLD_CR_BRAND = 3,
	FLD_CR_STOCK_TYPE = 4, FLD_CR_STOCK_PLACE = 5, FLD_CR_PAYMENT_METHOD = 6,
	FLD_CR_ADDRESS = 7, FLD_CR_DELIVERY_METHOD = 8, FLD_CR_ACCOUNT = 9, FLD_CR_JOB_TYPE = 10, FLD_CR_MACHINE_NAME = 11,
	FLD_CR_MACHINE_EVENT = 12,

	FLD_CALENDAR_ID = 0, FLD_CALENDAR_DAY_DATE = 1, FLD_CALENDAR_WEEK_NUMBER = 2, FLD_CALENDAR_MONTH = 3,
	FLD_CALENDAR_JOBS = 4, FLD_CALENDAR_PAYS = 5, FLD_CALENDAR_PAYS_USE = 6, FLD_CALENDAR_BUYS = 7, FLD_CALENDAR_BUYS_PAY = 8,
	FLD_CALENDAR_TOTAL_JOBPRICE_SCHEDULED = 9, FLD_CALENDAR_TOTAL_PAY_RECEIVED = 10,
	FLD_CALENDAR_TOTAL_BUY_BOUGHT = 11, FLD_CALENDAR_TOTAL_BUY_PAID = 12,

	FLD_MACHINES_ID = 0, FLD_MACHINES_SUPPLIES_ID = 1, FLD_MACHINES_NAME = 2, FLD_MACHINES_BRAND = 3, FLD_MACHINES_TYPE = 4,
	FLD_MACHINES_EVENTS_DESC = 5, FLD_MACHINES_EVENT_DATES = 6, FLD_MACHINES_EVENT_TIMES = 7, FLD_MACHINES_EVENT_JOBS = 8
};

enum ITEMS_AND_SERVICE_RECORD {
	ISR_NAME = 0, ISR_UNIT = 1, ISR_BRAND = 2, ISR_QUANTITY = 3, ISR_UNIT_PRICE = 4,
	ISR_TOTAL_PRICE = 5, ISR_SUPPLIER = 6, ISR_ID = 7, ISR_OWNER = 8, ISR_DATE = 9
};

enum PAY_HISTORY_RECORD
{
	PHR_DATE = 0, PHR_VALUE, PHR_PAID, PHR_METHOD, PHR_ACCOUNT, PHR_USE_DATE, PHR_EXTRA_INFO
};

enum SEARCH_CATEGORIES {
	SC_ID = 0, SC_REPORT_1, SC_REPORT_2, SC_ADDRESS_1, SC_ADDRESS_2, SC_ADDRESS_3,
	SC_ADDRESS_4, SC_ADDRESS_5, SC_PHONE_1, SC_PHONE_2, SC_PHONE_3,
	SC_PRICE_1, SC_PRICE_2, SC_DATE_1, SC_DATE_2, SC_DATE_3, SC_TIME_1,
	SC_TIME_2, SC_TYPE, SC_EXTRA_1, SC_EXTRA_2
};

#endif // GLOBAL_ENUMS_H
